version: '3'

volumes:
  db-data:
  mongo-config:

services:
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017-27019:27017-27019'
    env_file:
      - .env
    volumes:
    - db-data:/data/db
    - mongo-config:/data/configdb


